name: CD - Deploy Airflow (Astro)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash

      - name: Deploy to Astronomer
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_DEPLOYMENT_TOKEN }}
        run: |
          astro deploy "${{ secrets.ASTRO_DEPLOYMENT_ID }}" --force
