name: CD - Deploy Airflow with Astro

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Install Astro CLI
      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash

      # 3️⃣ Login to Astronomer (TOKEN)
      - name: Login to Astronomer
        run: |
          astro login https://cloud.astronomer.io \
            --token-login ${{ secrets.ASTRO_API_TOKEN }}

      # 4️⃣ Deploy
      - name: Deploy Airflow
        run: |
          astro deploy
